services:
  data_service:
    build:
      context: .
      dockerfile: Containerfile.data
    image: cosmic_explorer_data
    volumes:
      - ./data:/workspace/data
      - ./scripts:/workspace/scripts:ro
      - ./requirements.txt:/workspace/requirements.txt:ro
      - ./podman-compose.yml:/workspace/podman-compose.yml:ro
      - ./Containerfile.data:/workspace/Containerfile.data:ro
      - ./desktop_app:/workspace/desktop_app:ro
    # GPU support for Windows/WSL2
    security_opt:
      - label=disable
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=${DISPLAY:-:0}
      - PYTHONUNBUFFERED=1
      - MPLBACKEND=Agg
      - PYTHONPATH=/workspace
      - CUDA_VISIBLE_DEVICES=0
    stdin_open: true
    tty: true
    # For GPU access on Windows
    privileged: false
    # Note: GPU support requires additional configuration on Windows

  desktop_app:
    build:
      context: .
      dockerfile: Containerfile.desktop
    image: cosmic_explorer_desktop
    volumes:
      - ./data:/workspace/data
      - ./desktop_app:/workspace/desktop_app:ro
      - ./scripts:/workspace/scripts:ro
      - ./requirements.txt:/workspace/requirements.txt:ro
      - ./podman-compose.yml:/workspace/podman-compose.yml:ro
      - ./Containerfile.desktop:/workspace/Containerfile.desktop:ro
    # GPU and display support
    security_opt:
      - label=disable
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      - DISPLAY=${DISPLAY:-:0}
      - PYTHONPATH=/workspace
      - CUDA_VISIBLE_DEVICES=0
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_X11_NO_MITSHM=1
    stdin_open: true
    tty: true
    # Note: GPU support requires additional configuration on Windows
    # For GUI applications (Windows compatibility)
    # network_mode: host  # Commented out for Windows compatibility

  web_portal:
    build:
      context: .
      dockerfile: Containerfile.web
    image: cosmic_explorer_web
    ports:
      - "3000:3000"
    volumes:
      - ./data/processed:/app/public/data:ro
      - ./web_portal:/app/web_portal:ro
      - ./podman-compose.yml:/app/podman-compose.yml:ro
      - ./Containerfile.web:/app/Containerfile.web:ro
    stdin_open: true
    tty: true
